version: "2"

services:
  app:
    build: .
    container_name: "app"
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=admin
      - DB_NAME=/jdbc/datasources/libmovie
      - DB_USER=mysql
      - DB_PASS=mysql
      - DB_URI=db:3306
    depends_on:
      - db
    ports:
      - "8080:8080" # application
      - "9990:9990" # admin console
      - "8787:8787" # debug interface

  db:
    container_name: "db"
    image: "mariadb:latest"
    environment:
      - MYSQL_DATABASE=libmovie
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/ # init database
      - ./db/data/:/var/lib/mysql/ # data storage
    ports:
      - "3306:3306"

networks:
  default:
    driver: bridge