use `libmovie`;

insert into `users` 
	(
		`username`,
        `password`,
        `firstname`,
        `lastname`,
        `email`
	)
    values
    (
		"pete842",
        "totem",
        "Pierre",
        "Kohler",
        "pete842@mail.com"
    ),
    (
		"jzaehrin",
        "totem",
        "Jonathan",
        "Zaehringer",
        "jzaehrin@mail.com"
    ),
    (
		"capito27",
        "totem",
        "Filipe",
        "Fortunato",
        "capito27@mail.com"
    );
    
insert into `users` 
    (
        `username`,
        `password`,
        `firstname`,
        `lastname`,
        `email`
    )
    values
    (
        "pete842",
        "totem",
        "Pierre",
        "Kohler",
        "pete842@mail.com"
    ),
    (
        "jzaehrin",
        "totem",
        "Jonathan",
        "Zaehringer",
        "jzaehrin@mail.com"
    ),
    (
        "capito27",
        "totem",
        "Filipe",
        "Fortunato",
        "capito27@mail.com"
    )
